List<Map<String, String>> projects1 = [
  {
    "asset": "assets/newspak.png",
    "title": "NewsPak",
    "description": "Superior Multi-channel news app with advanced features",
    "isAsset": "asset",
    "onPlayStore": "PlayStore",
    "isLogo": "logo",
    "playLogo": "assets/logoNewsPak.png",
    "playLink":
        "https://play.google.com/store/apps/details?id=com.montagmakes.news_pakistan",
    "onGit": "",
    "gitLink": "",
    "webLink": "",
  },
  
  {
    "asset": "assets/propak.png",
    "title": "ProPak",
    "description": "ProPakistani news app with advanced features",
    "isAsset": "asset",
    "onPlay": "PlayStore",
    "isLogo": "logo",
    "playLogo": "assets/logoProPak.png",
    "playLink":
        "https://play.google.com/store/apps/details?id=com.taxfiler.propakistani",
    "onGit": "",
    "gitLink": "https://github.com/MontagMakes/ProPakistani",
    "webLink": "",
  },
  {
    "asset": "etch.png",
    "title": "Etch-a-Sketch",
    "description": "Color paint board website Made in html/css/javascript",
    "isAsset": "asset",
    "onPlay": "PlayStore",
    "isLogo": "",
    "playLink": "",
    "onGit": "",
    "gitLink": "https://github.com/MontagMakes/Etch-a-Sketch",
    "webLink": "https://montagmakes.github.io/Etch-a-Sketch/",
  },
  {
    "asset": "rock.png",
    "title": "Rock-paper-scissors",
    "description": "Game in a website Made in html/css/javascript",
    "isAsset": "asset",
    "onPlay": "PlayStore",
    "isLogo": "",
    "playLink": "",
    "onGit": "",
    "gitLink": "https://github.com/MontagMakes/rock-paper-scissors",
    "webLink": "https://montagmakes.github.io/rock-paper-scissors/",
  },
  {
    "asset": "website.png",
    "title": "MontagMakes",
    "description": "Portfolio Website made in flutter web",
    "onPlayStore": "PlayStore",
    "playLogo": "assets/logoNewsPak.png",
    "playLink":"",
    "gitLink": "https://github.com/MontagMakes/portfolio_website",
    "webLink": "",
  },
  {
    "asset": "assets/tribune.png",
    "title": "The Tribune",
    "description": "Express Tribune news app with advanced features",
    "isAsset": "asset",
    "onPlay": "PlayStore",
    "isLogo": "logo",
    "playLogo": "assets/logoTribune.png",
    "playLink":
        "https://play.google.com/store/apps/details?id=com.montagmakes.tribune",
    "onGit": "",
    "gitLink": "https://github.com/MontagMakes/tribune_app",
    "webLink": "",
  },
];

List<String> techStack = [
  'Flutter',
  'Dart',
  'Firebase',
  'Firebase Functions',
  'Flutter web',
  'Python',
  'Web-Scraping',
  'Selenium',
  'Git',
  'GitHub',
  'HTML',
  'CSS',
  'JavaScript',
];
